/*
 *  Copyright (c) 2026
 *  Agnieszka Sorensen
 */

//////////////////////////////////////////////////////////////////////////////////////////
// This class is based off of a class automatically generated by ROOT with the
// [root_tree]->MakeClass("class_name") command, but has been considerably adjusted.
//////////////////////////////////////////////////////////////////////////////////////////

#ifndef SMASH_ROOT_ANALYSIS_READ_PARTICLES_H
#define SMASH_ROOT_ANALYSIS_READ_PARTICLES_H

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>

#include "./constants.h"




//////////////////////////////////////////////////////////////////////////////////////////
// ReadParticles is a class to read in ROOT files and enable analysis.

class ReadParticles {
 public:
  // Pointer to the analyzed TTree or TChain
  TChain* fChain;
  // Current Tree number in a TChain
  Int_t fCurrent;

  

  ////////////////////////////////////////////////////////////////////////////////////////
  // Declaration of leaf types; this is specific to the SMASH Particles.root file.  
  Int_t ev;
  Int_t ens;
  Int_t tcounter;
  Int_t npart;
  Int_t test_p;
  Double_t modus_l;
  Double_t current_t;
  Double_t impact_b;
  Int_t empty_event;
  Int_t id[Max_Particles]; 
  Int_t pdgcode[Max_Particles];
  Int_t charge[Max_Particles];
  Double_t formation_time[Max_Particles];
  Double_t time_last_collision[Max_Particles];
  Double_t p0[Max_Particles];
  Double_t px[Max_Particles];
  Double_t py[Max_Particles];     
  Double_t pz[Max_Particles];   
  Double_t t[Max_Particles];
  Double_t x[Max_Particles];       
  Double_t y[Max_Particles];    
  Double_t z[Max_Particles];        
  Double_t E_kinetic_tot;
  Double_t E_fields_tot;
  Double_t E_tot;
  bool MF_output;
  bool coll_output;
  
  ////////////////////////////////////////////////////////////////////////////////////////
  // List of branches; this is specific to the SMASH Particles.root file.  
  TBranch* b_ev;
  TBranch* b_ens;
  TBranch* b_tcounter;
  TBranch* b_npart;
  TBranch* b_test_p;
  TBranch* b_modus_l;
  TBranch* b_current_t;
  TBranch* b_impact_b;
  TBranch* b_empty_event;
  TBranch* b_id;
  TBranch* b_pdgcode;
  TBranch* b_charge;
  TBranch* b_formation_time;
  TBranch* b_time_last_collision;
  TBranch* b_p0;
  TBranch* b_px;
  TBranch* b_py;
  TBranch* b_pz;
  TBranch* b_t;
  TBranch* b_x;
  TBranch* b_y;
  TBranch* b_z;
  TBranch* b_E_kinetic_tot;
  TBranch* b_E_fields_tot;
  TBranch* b_E_tot;
  TBranch* b_MF_output;
  TBranch* b_coll_output;

  ////////////////////////////////////////////////////////////////////////////////////////
  // Auxiliary variables to prevent accessing non-existing branches in ROOT files with
  // standard output
  bool id_branch_exists{};
  bool formation_time_branch_exists{};
  bool time_last_collision_branch_exists{};
  bool MF_output_branch_exists{};
  bool coll_output_branch_exists{};


  
  ////////////////////////////////////////////////////////////////////////////////////////
  // Default constructor
  ReadParticles();

  // Alternative constructor 1
 ReadParticles(int folder_min,
	       int no_of_directories);

  // Alternative constructor 2
  ReadParticles(std::string ROOT_file_address);

  // Destructor
  virtual ~ReadParticles();

  

  ////////////////////////////////////////////////////////////////////////////////////////
  // Member functions of the class; because they're virtual, they can be overriden if used
  // in a derived class.
  virtual Int_t GetEntry(Long64_t entry);
  virtual Long64_t LoadTree(Long64_t entry);
  virtual void Init(TChain *tree);
  virtual Bool_t Notify();
  virtual void Show(Long64_t entry = -1);
  //
  //
  //
  virtual void get_properties();

  

  ////////////////////////////////////////////////////////////////////////////////////////
  // Return functions for private ROOTFileProperties struct members
  Long64_t n_entries() const { return ROOT_file_properties_.n_entries(); }
  int n_events() const { return ROOT_file_properties_.n_events(); }
  int n_event_outputs() const { return ROOT_file_properties_.n_event_outputs(); }
  int n_event_time_steps() const { return ROOT_file_properties_.n_event_time_steps(); }
   double output_interval()const  { return ROOT_file_properties_.output_interval(); }
  double max_time() const { return ROOT_file_properties_.max_time(); }
  int n_test() const { return ROOT_file_properties_.n_test(); }
  int n_ensembles() const { return ROOT_file_properties_.n_ensembles(); }
  double box_length() const { return ROOT_file_properties_.box_length(); }
  int number_of_particles_at_init() const {
    return ROOT_file_properties_.number_of_particles_at_init();
  }  
  std::vector<double> time_steps() const { return ROOT_file_properties_.time_steps(); }
  std::vector<double> current_t_steps() const {
    return ROOT_file_properties_.current_t_steps();
  }


  
 private:
  void print_ROOT_file_properties() const;
  
  // For metadata file handling:
  // Extracting out ROOT file properties (metadata) can be extremely time-consuming, but
  // it only needs to be done once for a given, fixed data set. The variables below enable
  // checking whether the metadata has already been extracted and that it corresponds to
  // the current data set. If so, the full extraction is skipped.
  
  // Method to compute a hash = a short summary number (a unique fingerprint) that changes
  // whenever the underlying data (number of files, file order, file content) changes
  size_t compute_chain_hash() const;
  // Method to load the metadata (if valid)
  bool load_metadata_if_valid(size_t hash);
  // Method to save the metadata
  void write_metadata(size_t hash) const;
  // Metadata file path and name:
  std::string metadata_file_name_;
  // A vector of chain file paths used for fingerprint hash:
  std::vector<std::string> chain_file_paths_;
  

  
  ///////////////////////////////////////////
  // Basic information recovered about the ROOT file. We put all that information into a
  // struct with its own set() and get() functions so that it is less likely that the
  // quantities (which are not const) are overwritten by chance.
  struct ROOTFileProperties {

    // Return functions
    Long64_t n_entries() const { return n_entries_; }
    int n_events() const { return n_events_; }
    int n_event_outputs() const { return n_event_outputs_; }
    int n_event_time_steps() const { return n_event_time_steps_; }
    double output_interval() const { return output_interval_; }
    double max_time() const { return max_time_; }
    int n_test() const { return n_test_; }
    int n_ensembles() const { return n_ensembles_; }
    double box_length() const { return box_length_; }
    int number_of_particles_at_init() const { return number_of_particles_at_init_; }   
    std::vector<double> time_steps() const { return time_steps_; }
    std::vector<double> current_t_steps() const { return current_t_steps_; }

  private:
    void set_n_entries(Long64_t value) { n_entries_ = value; }
    void set_n_events(int value) { n_events_ = value; }
    void set_n_event_outputs(int value) { n_event_outputs_ = value; }
    void set_n_event_time_steps(int value) { n_event_time_steps_ = value; }
    void set_output_interval(double value) { output_interval_ = value; }
    void set_max_time(double value) { max_time_ = value; }
    void set_n_test(int value) { n_test_ = value; }
    void set_n_ensembles(int value) { n_ensembles_ = value; }    
    void set_box_length(double value) { box_length_ = value; }
    void set_number_of_particles_at_init(int value) {
      number_of_particles_at_init_ = value;
    }
    void set_time_steps(std::vector<double> v) { time_steps_ = v; }
    void set_current_t_steps(std::vector<double> v) { current_t_steps_ = v; }

    // Only ReadParticles can call set()
    friend class ReadParticles;

    // Members:
    // Properties are initialized to absurd values so that it is clear when they are updated
    // (with the exception of vectors, which are brace-initialized to be of length zero).
    
    // number of entries = all time steps across all events, including ensembles
    Long64_t n_entries_ = -100;
    // number of events
    int n_events_ = -100;
    // number of outputs within one event (across all ensembles)
    int n_event_outputs_ = -100;
    // number of steps within one event (within one ensemble)
    int n_event_time_steps_ = -100;
    // output interval
    double output_interval_ = -100.0;
    // maximum time in the evolution
    double max_time_ = -100.0;
    // number of test particles per particle
    int n_test_ = -100;
    // number of ensembles
    int n_ensembles_ = -100;
    // box length
    double box_length_ = -100.0;
    // number of particles at initialization, initialized to a stupid value
    int number_of_particles_at_init_ = -100;
    // a vector of time steps
    std::vector<double> time_steps_{};
    // a vector of current_t steps
    std::vector<double> current_t_steps_{};
  };

  // All read out properties combined in one struct:
  ROOTFileProperties ROOT_file_properties_;
};

#endif
